version: '2.2'

services:
  postgres:
    hostname: postgres
    image: mdillon/postgis

  slave:
    build: jenkinsslave1
    scale: 8
    environment:
      - ANOTHER_SSH_HOST=another_machine
      - ANOTHER_SSH_PASS=very_secret

  jenkinsdockerslave1:
    container_name: jenkinsdockerslave1
    build: jenkinsdockerslave1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker

  jenkins:
    build: jenkins
    container_name: jenkins
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:50000:50000"
    links:
      - jenkinsdockerslave1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker

  jenkinssetup:
    container_name: jenkinssetup
    build: jenkinssetup
    links:
      - jenkins

  #jenkinsswarmslave1:
  #  container_name: jenkinsswarmslave1
  #  build: jenkinsswarmslave1
  #  links:
  #    - jenkins
